[package]
name = "polyglot-zipper"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.0", features = ["derive"] }
iconv = "0.1.1"
zip = "0.6.6"

[[bin]]
name = "polyzip"
path = "src/main.rs"